# Generated by Django 2.1 on 2018-08-24 10:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bTitle', models.CharField(max_length=30)),
                ('bType', models.CharField(max_length=30)),
                ('bAuthor', models.CharField(max_length=30)),
                ('bComment', models.TextField(default='', max_length=200)),
                ('bPubDate', models.DateField(default=datetime.date.today)),
                ('bRead', models.BooleanField(default=False)),
                ('bTxt', models.FileField(max_length=200, upload_to='./Txt/')),
                ('bUrl', models.URLField(blank=True)),
                ('bCover', models.ImageField(height_field=100, max_length=200, upload_to='./Image/', width_field=150)),
            ],
        ),
        migrations.CreateModel(
            name='God',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gName', models.CharField(max_length=30)),
                ('gAge', models.IntegerField(blank=True)),
                ('gEmail', models.EmailField(default='', max_length=254, unique=True)),
                ('gLastReadDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hName', models.CharField(max_length=30)),
                ('hGender', models.CharField(max_length=1)),
                ('hContent', models.TextField(default='', max_length=200)),
                ('hBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.BookInfo')),
            ],
        ),
    ]
