# Generated by Django 2.1 on 2018-08-25 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='bRead',
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='bHaveRead',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bAuthor',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bComment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bCover',
            field=models.ImageField(blank=True, height_field=100, max_length=200, upload_to='./Image/', width_field=150),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bPubDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bTxt',
            field=models.FileField(blank=True, max_length=200, upload_to='./Txt/'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bType',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hContent',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hGender',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
